
status:


error

cannot run it.


_____________


goal:

run the app from.. 
https://ultimatedjango.com/learn-django/chapters/
url = https://github.com/tabdon/crmeasyapp

_____________




Attaching to ultitabdon_djdev_1
djdev_1    | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f484445fb00>
djdev_1    | Traceback (most recent call last):
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
djdev_1    |     fn(*args, **kwargs)
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
djdev_1    |     autoreload.raise_last_exception()
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
djdev_1    |     six.reraise(*_exception)
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
djdev_1    |     raise value.with_traceback(tb)
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
djdev_1    |     fn(*args, **kwargs)
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 18, in setup
djdev_1    |     apps.populate(settings.INSTALLED_APPS)
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 108, in populate
djdev_1    |     app_config.import_models(all_models)
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 198, in import_models
djdev_1    |     self.models_module = import_module(models_module_name)
djdev_1    |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
djdev_1    |     return _bootstrap._gcd_import(name[level:], package, level)
djdev_1    |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
djdev_1    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
djdev_1    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
djdev_1    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
djdev_1    |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
djdev_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
djdev_1    |   File "/code/crmapp/accounts/models.py", line 4, in <module>
djdev_1    |     from shortuuidfield import ShortUUIDField
djdev_1    |   File "/usr/local/lib/python3.7/site-packages/shortuuidfield/__init__.py", line 4
djdev_1    |     except Exception, e:
djdev_1    |                     ^
djdev_1    | SyntaxError: invalid syntax


